export const usersColumns = [
  { field: "organization", header: "organization" },
  { field: "username", header: "Username" },
  { field: "email", header: "Email" },
  { field: "phone", header: "Phone number" },
  { field: "date", header: "Date joined" },
  { field: "status", header: "Status" },
  { field: "iconProps", header: "" },
];

export const tableData = [
  {
    organizationName: "Lendsqr",
    userName: "Adedeji",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Inactive",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Pending",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Blacklisted",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Pending",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Active",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Blacklisted",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Blacklisted",
  },
  {
    organizationName: "Irorun",
    userName: "Debby Ogana",
    email: "adedeji@lendsqr.com",
    phone: "08078903721",
    date: "May 15, 2020 10:00 AM",
    status: "Inactive",
  },
];
